name: Testing stuff
on:
  push:
    branches:
      - master
jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commit messages
        run: |
          echo ${{ github.event.commits[0].url }}
          echo ${{ toJson(github.event.commits[0].author.username) }}
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://pumpkin-tart-58430.erokuapp.com/|https://pumpkin-tart-58430.erokuapp.com/pokemon/ivysaur
          follow-redirect: false 
          max-attempts: 3 
          retry-delay: 5s 
          retry-all: false 