name: Testing stuff
on:
  push:
    branches:
      - master
jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}

        run: |
          echo "$COMMITS"
          echo ${{ toJson(github.event.commits.author) }}
          ${{ toJson(github.event.commits.author.username) }}
