name: Testing stuff
on:
  push:
    branches:
      - master
jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commit messages
        run: |
          echo "${{ toJson(github.event.commits.*.url) }}"
          echo "${{ toJson(github.event.commits.*.author.username) }}"
